# site settings
title: Kangbo Lu
subtitle: Data Scientist Consultant
email: kblu@ucdavis.edu
description: Software engineer, data scientist, and fingerstyle guitarist.
baseurl:
url:
author: Kangbo Lu
street_address: Dag hammarskjöld 3477
city: Vitacura, Santiago
state: Región Metropolitana de Santiago
zip_code: 7630000
country: Chile
phone: Unavailable for public

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/KangboLu
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/kangbolu/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
